#ifndef DATABASE_H
#define DATABASE_H

#include <string>
#include <sqlite3.h>

class Database {
  sqlite3 *database;
  std::string db_name;
  std::string sql_statement;
  int current_activity_index;
public:
  Database();
  ~Database();
  bool openDatabase();                                           //opens the database and creates the databas.db file when not happened yet
  bool closeDatabase();                                          //clode the database
  bool createTable();                                            //create the table, we have only one table with all informations 
  bool insertActivityItem(std::string activity);                 //insert only one and new activity row
  bool updateEstimatedPromodoro(int activity_index, int numbers);  //insert or update the estimated pomodoro for an activity
  bool updatePomodoro(int activity_index);                       //increase the pomodoro column value by one for selected activity
  bool selectDayToDoTodayActivity(int activity_index);           //copies an item to the DayToDoToday List
  bool markActivityFinished(int activity_index);                 //a comlete activity is done
  bool insertExternalInterrupt(int activity_index);              //external interrupt occured
  bool insertInternalInterrupt(int activity_index);              //internal interrupt occured
  bool insertUnplannedUrgentActivity(int activity_index);        //insert the activity generated by the interupt into the table
};

#endif
